# Generated by Django 2.2.6 on 2020-02-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
    ]
