# Generated by Django 2.2.6 on 2020-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200209_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_dislikes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_likes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_dislikes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_likes',
            field=models.IntegerField(default=1),
        ),
    ]
