# Generated by Django 2.2.6 on 2020-02-09 12:55

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200209_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='photo',
            field=models.ImageField(upload_to=home.models.user_directory_path),
        ),
    ]
