# Generated by Django 2.2.6 on 2020-02-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pic_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='user_id',
            new_name='user',
        ),
    ]
